In [1]:
from eventregistry import EventRegistry, QueryArticles
from transformers import AutoTokenizer, pipeline
from sqlalchemy import create_engine
import psycopg2
from psycopg2.extras import execute_values
import pandas as pd
import requests
from datetime import datetime, timezone
import numpy as np
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

/Users/davorangelov/IdeaProjects/das_proekt/Domasna_3/python/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
#the database connection URL for NeonDB
DATABASE_URL = "postgresql://neondb_owner:npg_kq8bTwuC2Byx@ep-quiet-mouse-agrjgu4z.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

engine = create_engine(
    DATABASE_URL,
    poolclass=psycopg2.pool.ThreadedConnectionPool if hasattr(psycopg2, 'pool') else None,
    pool_size=20,
    max_overflow=10,
    pool_pre_ping=True,
)
def get_db_connection():
    return psycopg2.connect(DATABASE_URL)

In [3]:

er = EventRegistry(apiKey="2ea8797a-b87e-4577-b83c-6edcd1b34984")

q = QueryArticles(keywords="bitcoin", lang="eng")
result = er.execQuery(q)

sentiment_df = pd.DataFrame(result['articles']['results'])

sentiment_df.drop(columns=['uri', 'lang', 'isDuplicate', 'time', 'sim', 'dateTime', 'dateTimePub', 'dataType', 'source', 'authors', 'image', 'eventUri', 'wgt', 'relevance'], inplace=True)

In [4]:
import torch
from transformers import pipeline, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")
finbert = pipeline("sentiment-analysis", model="ProsusAI/finbert")

def classify_sentiment(text):
    if pd.isna(text) or not text.strip():
        return 'neutral'
    # Tokenize and truncate to 512 tokens
    tokens = tokenizer(text, truncation=True, max_length=512, return_tensors='pt')
    # Convert back to string (optional, but pipeline can handle tokens)
    truncated_text = tokenizer.decode(tokens['input_ids'][0], skip_special_tokens=True)
    result = finbert(truncated_text)[0]
    return result['label']

sentiment_df['finbert_sentiment'] = sentiment_df['body'].apply(classify_sentiment)
sentiment_df['body'] = sentiment_df['body'].str.slice(0, 255)
sentiment_df

Device set to use mps:0

,date,url,title,body,sentiment,finbert_sentiment
0,2025-12-15,https://cardanofeed.com/here-are-the-most-popu...,Here are the most popular 2025 blockchains · C...,Following a monumental year for the cryptocurr...,0.552941,positive
1,2025-12-15,https://www.benzinga.com/markets/equities/25/1...,"Tesla Eyes Record Highs, Bitcoin Tumbles To $8...",Wall Street traded little changed Monday after...,0.145098,negative
2,2025-12-15,https://newsable.asianetnews.com/markets/gold-...,"Gold Is Up 65% YTD, But Howard Marks Says The ...","The Oaktree co-founder, also known for his inv...",0.082353,neutral
3,2025-12-15,https://www.benzinga.com/news/25/12/49400030/c...,Crude Oil Falls Over 1%; US Homebuilder Sentim...,U.S. stocks traded lower midway through tradin...,0.317647,negative
4,2025-12-15,https://www.cbssports.com/college-football/new...,"Expert reveals College Football Playoff picks,...",Eight teams take the field this weekend for th...,0.176471,neutral
...,...,...,...,...,...,...
95,2025-12-15,https://coinigy.medium.com/crypto-scams-rise-a...,Crypto Scams Rise as Netflix Lose Millions in ...,"So guys, it looks like even crypto royalty isn...",-0.270588,neutral
96,2025-12-15,https://sherwood.news/markets/nvidias-favorite...,Nvidia's favorite stocks are getting shellacke...,"Nvidia's ""House of GPUs"" is looking a little w...",0.215686,negative
97,2025-12-15,https://crypto-economy.com/michael-saylors-str...,"Michael Saylor's Strategy Adds 10,645 BTC in $...","Between December 8 and December 14, the compan...",0.074510,negative
98,2025-12-15,https://www.benzinga.com/crypto/cryptocurrency...,"Crypto Can No Longer Be Ignored Or Dismissed, ...",Enter your email to get Benzinga's ultimate mo...,0.333333,positive
99,2025-12-15,https://www.crypto-reporter.com/newsfeed/the-m...,The Marygold Companies' USCF Investments Subsi...,"SAN CLEMENTE, Calif.--(BUSINESS WIRE)--The Mar...",0.317647,neutral

In [5]:

conn = get_db_connection()
cursor = conn.cursor()
rows = list(sentiment_df[['date', 'url', 'title', 'body', 'sentiment', 'finbert_sentiment']].itertuples(index=False, name=None))
execute_values(
    cursor,
    """
    INSERT INTO sentiment (date, url, title, body, sentiment, finbert_sentiment)
    VALUES %s
    ON CONFLICT DO NOTHING
    """,
    rows
)

conn.commit()
cursor.close()
conn.close()

In [6]:
import requests
import pandas as pd
from datetime import datetime, timezone

def get_onchain_metrics_history(api_key, slug):
    url = "https://api.santiment.net/graphql"
    headers = {
        "Authorization": f"Apikey {api_key}",
        "Content-Type": "application/json"
    }
    metrics = {
        "active_addresses": "daily_active_addresses",
        "transactions_count": "transactions_count",
        "exchange_inflow": "exchange_inflow",
        "whale_transactions": "whale_transaction_count_1m_usd_to_inf",
        "nvt": "nvt",
        "mvrv": "mvrv_usd"
    }
    all_data = {}

    # Set the date range for the last year
    from_date = "2024-12-14T00:00:00Z"
    to_date = "2025-12-14T23:59:59Z"
    interval = "1d"

    for display_name, metric_name in metrics.items():
        query = f"""
        {{
          getMetric(metric: "{metric_name}") {{
            timeseriesData(
              slug: "{slug}"
              from: "{from_date}"
              to: "{to_date}"
              interval: "{interval}"
            ) {{
              datetime
              value
            }}
          }}
        }}
        """
        response = requests.post(url, headers=headers, json={"query": query})
        data = response.json()

        if 'errors' in data:
            print(f"Error fetching {display_name}: {data['errors']}")
            continue
        else:
            timeseries = data['data']['getMetric']['timeseriesData']
            if timeseries:
                # Extract datetime and value, convert to DataFrame
                df_metric = pd.DataFrame(timeseries)
                df_metric['datetime'] = pd.to_datetime(df_metric['datetime'])
                df_metric.set_index('datetime', inplace=True)
                df_metric.rename(columns={'value': display_name}, inplace=True)
                all_data[display_name] = df_metric
            else:
                print(f"No data for {display_name}")

    # Merge all metrics into one DataFrame
    if all_data:
        df_combined = pd.concat(all_data.values(), axis=1)
        return df_combined
    else:
        return pd.DataFrame()

# Example usage
api_key = "ldieg4tvzgd7baf7_bfqjp6kvbyg6fesc" 
slug = "bitcoin"  

on_chain_metrics = get_onchain_metrics_history(api_key, slug)

In [8]:
on_chain_metrics = on_chain_metrics.fillna(0).fillna(method='ffill')
on_chain_metrics = on_chain_metrics.replace([np.inf, -np.inf], 0)

on_chain_metrics = on_chain_metrics.fillna(method='ffill')
on_chain_metrics['active_addresses'] = on_chain_metrics['active_addresses'].round().astype(int)
on_chain_metrics['transactions_count'] = on_chain_metrics['transactions_count'].round().astype(int)
on_chain_metrics['whale_transactions'] = on_chain_metrics['whale_transactions'].round().astype(int)
print(on_chain_metrics.info())

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 366 entries, 2024-12-14 00:00:00+00:00 to 2025-12-14 00:00:00+00:00
Freq: D
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   active_addresses    366 non-null    int64
 1   transactions_count  366 non-null    int64
 2   exchange_inflow     366 non-null    float64
 3   whale_transactions  366 non-null    int64
 4   nvt                 366 non-null    float64
 5   mvrv                366 non-null    float64
dtypes: float64(3), int64(3)
memory usage: 20.0 KB
None

/var/folders/gn/2wn0n__s5rg50xs0vw68d57w0000gn/T/ipykernel_74863/433294066.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  on_chain_metrics = on_chain_metrics.fillna(0).fillna(method='ffill')
/var/folders/gn/2wn0n__s5rg50xs0vw68d57w0000gn/T/ipykernel_74863/433294066.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  on_chain_metrics = on_chain_metrics.fillna(method='ffill')

In [9]:
def fetch_crypto_id_by_coin_gecko_id(coin_gecko_id):
    conn = get_db_connection()

    query = "SELECT id FROM crypto WHERE coin_gecko_id = %s"
    df = pd.read_sql(query, conn, params=(coin_gecko_id,))

    conn.close()

    if df.empty:
        return None

    return int(df.iloc[0]["id"])

In [10]:
def save_onchain_metrics_to_db(df, coin_gecko_id):
    """
    Save on-chain metrics DataFrame to the database.
    :param df: DataFrame with on-chain metrics, index as date
    :param coin_gecko_id: The coinGeckoId of the cryptocurrency
    """
    crypto_id = fetch_crypto_id_by_coin_gecko_id(coin_gecko_id)
    if not crypto_id:
        raise ValueError(f"No crypto found with coinGeckoId: {coin_gecko_id}")

    conn = get_db_connection()
    cursor = conn.cursor()

    for date, row in df.iterrows():
        # Insert into on_chain table
        cursor.execute(
            """
            INSERT INTO on_chain (date, active_addresses, transactions_count, exchange_inflow, whale_transactions, nvt, mvrv)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            RETURNING id;
            """,
            (
                date.date(),
                int(row.get('active_addresses')),
                int(row.get('transactions_count')),
                float(row.get('exchange_inflow')),
                int(row.get('whale_transactions')),
                float(row.get('nvt')),
                float(row.get('mvrv'))
            )
        )
        on_chain_id = cursor.fetchone()[0]

        # Insert into crypto_on_chain table
        cursor.execute(
            """
            INSERT INTO crypto_on_chain (crypto_id, on_chain_id)
            VALUES (%s, %s);
            """,
            (crypto_id, on_chain_id)
        )

    conn.commit()
    cursor.close()
    conn.close()

coin_gecko_id = "tether"  
save_onchain_metrics_to_db(on_chain_metrics, coin_gecko_id)

/var/folders/gn/2wn0n__s5rg50xs0vw68d57w0000gn/T/ipykernel_74863/2701956634.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=(coin_gecko_id,))

In [11]:
def fetch_sentiment():
    conn = get_db_connection()

    query = """
        SELECT finbert_sentiment FROM sentiment
    """

    df = pd.read_sql(query, conn)

    conn.close()

    return df if not df.empty else pd.DataFrame()

In [12]:
def fetch_onchain_by_crypto_id(crypto_id):
    conn = get_db_connection()

    query = """
        SELECT *
        FROM crypto_on_chain coc
        JOIN on_chain oc ON coc.on_chain_id = oc.id
        WHERE coc.crypto_id = %s
    """

    df = pd.read_sql(query, conn, params=(crypto_id,))

    conn.close()

    return df if not df.empty else pd.DataFrame()

In [13]:
def fetch_crypto_price_by_crypto_id(crypto_id):
    connection = get_db_connection()
    query = """
        SELECT date, close
        FROM price
        WHERE crypto_id = %s
    """
    df = pd.read_sql(query, connection, params=[crypto_id])
    connection.close()
    return df.dropna()

In [17]:
crypto_id = fetch_crypto_id_by_coin_gecko_id('bitcoin')
df_sentiment = fetch_sentiment()

# Get dataframes safely
price_df = fetch_crypto_price_by_crypto_id(crypto_id)
onchain_df = fetch_onchain_by_crypto_id(crypto_id)

# Handle empty onchain data
if onchain_df.empty:
    df_onchain_price = price_df.copy()
    df_onchain_price['active_addresses'] = 0
    df_onchain_price['transactions_count'] = 0
    df_onchain_price['whale_transactions'] = 0
else:
    df_onchain_price = pd.merge(price_df, onchain_df, on='date', how='left')

df = pd.concat([df_onchain_price, df_sentiment], axis=1)
df = df.dropna(subset=['date'])  # Clean final dataframe
df.head()

/var/folders/gn/2wn0n__s5rg50xs0vw68d57w0000gn/T/ipykernel_74863/2701956634.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=(coin_gecko_id,))
/var/folders/gn/2wn0n__s5rg50xs0vw68d57w0000gn/T/ipykernel_74863/127940581.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)
/var/folders/gn/2wn0n__s5rg50xs0vw68d57w0000gn/T/ipykernel_74863/606572085.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=(crypto_id,))

,date,close,active_addresses,transactions_count,whale_transactions,finbert_sentiment
0,2022-04-08,26.87,0,0,0,positive
1,2019-05-02,4.59,0,0,0,negative
2,2019-05-03,5.31,0,0,0,neutral
3,2019-05-04,5.26,0,0,0,negative
4,2019-05-05,4.85,0,0,0,neutral

In [19]:
df["predict"] = (df["close"] > df["close"].shift(1)).astype(int)
df['sentiment'] = df['finbert_sentiment'].apply(lambda x: 0 if x == 'negative' else 1 if x == 'neutral' else 2)

# drop only columns that exist
columns_to_drop = ['id', 'crypto_id', 'on_chain_id', 'finbert_sentiment', 'date']
existing_columns = [col for col in columns_to_drop if col in df.columns]
df.drop(columns=existing_columns, inplace=True)

df

,close,active_addresses,transactions_count,whale_transactions,predict,sentiment
0,26.87,0,0,0,0,2
1,4.59,0,0,0,0,0
2,5.31,0,0,0,1,1
3,5.26,0,0,0,0,0
4,4.85,0,0,0,0,1
...,...,...,...,...,...,...
2414,31.96,0,0,0,1,2
2415,30.89,0,0,0,0,2
2416,29.33,0,0,0,0,2
2417,26.90,0,0,0,0,2
2418,27.72,0,0,0,1,2

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2419 entries, 0 to 2418
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   close               2419 non-null   float64
 1   active_addresses    2419 non-null   int64
 2   transactions_count  2419 non-null   int64
 3   whale_transactions  2419 non-null   int64
 4   predict             2419 non-null   int64
 5   sentiment           2419 non-null   int64
dtypes: float64(1), int64(5)
memory usage: 113.5 KB

In [21]:
X, y = df.drop(columns=['predict']), df['predict']
train_x, test_x, train_y, test_y = train_test_split(X, y, test_size=0.2)
xgb = XGBClassifier(random_state=42)
xgb.fit(train_x, train_y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [22]:
pred_y = xgb.predict(test_x)
print(classification_report(test_y, pred_y))
print(confusion_matrix(test_y, pred_y))

              precision    recall  f1-score   support

           0       0.51      0.57      0.54       239
           1       0.52      0.46      0.49       245

    accuracy                           0.51       484
   macro avg       0.52      0.52      0.51       484
weighted avg       0.52      0.51      0.51       484

[[137 102]
 [133 112]]

In [23]:
import os
MODEL_PATH = "lstm_global.keras"
SCALER_PATH = "scaler_global.pkl"
os.path.exists(MODEL_PATH)

False